[UI][Enhancement] Navbar Blur
Front-End-Coders-Mauritius/frontendmu-astro pull request #75
Opened 2023-08-07 15:43 UTC by houzyk

Love the new nav! 

However, i noticed that when it's in front of something with a white background, we can't really see the navbar links (as that is white as well). Btw, this happens in dark mode on the FAQ page (https://frontend.mu/faq).

Current issue (notice we can't really read the nav links):

<img width="1438" alt="Screenshot 2023-08-07 at 19 21 41" src="https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/88334281/e028ea1d-cc74-401d-a1b3-d045c8e22fe5">

I simply made the back filter bright and we can see the text ok now.

Light mode proposed solution:

<img width="1438" alt="Screenshot 2023-08-07 at 19 34 36" src="https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/88334281/af9d1222-1422-49a2-87d1-40313fe93efd">

Dark mode proposed solution:

<img width="1438" alt="Screenshot 2023-08-07 at 19 41 25" src="https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/88334281/d5442c20-d162-4c15-b67e-6bfd3cd3b4a9">

Perks: improve accessbility and UX.

2023-08-07 16:57 UTC, MrSunshyne commented
Thanks for the UI improvement! 

The real problem here is that the FAQ section shouldn't be so bright in dark mode. That needs a fix soon. :P 
That being said, it is possible to have white elements behind the menu and the brightness fix is nice! 

I would still like to preserve the blur effect, I suggest something like `brightness(.7) blur(24px)` as a good balance between both meanwhile. WDYT?

2023-08-07 16:58 UTC, MrSunshyne requested changes

2023-08-07 16:58 UTC, MrSunshyne commented on src/components/MegaMenu.astro
> +    backdrop-filter: brightness(0.5);
let's try something like the following so that we don't lose the blur effect completely
backdrop-filter: brightness(.7) blur(24px)

2023-08-08 03:30 UTC, houzyk commented
Yeah, that lgtm as well!

blur 20 and brightness .8:

<img width="1438" alt="Screenshot 2023-08-08 at 07 27 30" src="https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/88334281/777606df-98a8-4d9e-a15c-65b521bb5197">

2023-08-08 03:36 UTC, houzyk commented
Housekeeping: added the command for copying .env.example to .env.development and removed redundant code block.

2023-08-08 07:14 UTC, merged

2023-08-08 07:18 UTC, MrSunshyne commented
@houzyk thanks for the env housekeeping. It's a little annoying in the initial clone, especially for new contributors. This makes it a little easier but perhaps we could do more? 

I was thinking of a a setup script that we could include in the readme. The setup script would have the responsibility of checking for missing files or dependencies in order for the project to start properly.

something like `npm run setup`

- Check for .env file
- Check if internet is available
- Check current node version
- Check if npm packages were installed
- Print current environment
- Exit

Just an idea after reading your comment, what do you think?

2023-08-08 14:58 UTC, houzyk commented
@MrSunshyne sounds like a neat thing to have. I'll see if i can make a lil something about this